Schema
kotofun/Junkyard pull request #7
Opened 2017-04-06 18:07 UTC by mixty1

2017-04-07 07:31 UTC, basavind requested changes
Схема не соответствует.

2017-04-07 07:45 UTC, basavind requested changes

2017-04-07 07:45 UTC, basavind commented on app/models/concerns/associate.rb
> +    end
Совершенно вредная и ненужная вещь — облегчает написание кода на 2 минуты и усложняет всё остальное.

2017-04-07 07:45 UTC, basavind commented on app/models/material.rb
> +  associate :has_one, [:license, :user, :rightholder, :state], dependent: :destroy
не надо объединять все сущности под одну гребенку с одинаковыми условиями — лучше явно объявить для каждой связи свои параметры.

Материал принадлежит лицензии, пользователю, правообладателю и стейту, о чем говорят ключи license_id, owner_id, rightholder_id и state_id в сущности материала, соответственно должно связь — `belongs_to` и триггер на удаление здесь не нужен.

2017-04-07 07:45 UTC, basavind commented on app/models/rightholder.rb
> +  belongs_to :material, dependent: :destroy
`has_many` без триггера `destroy`

2017-04-07 07:45 UTC, basavind commented on app/models/slice_type.rb
> +  belongs_to :slice, dependent: :destroy
`has_many` без `destroy`

2017-04-07 07:45 UTC, basavind commented on app/models/state.rb
> +  belongs_to :material, dependent: :destroy
`has_many` без `destroy`

2017-04-07 07:45 UTC, basavind commented on db/migrate/20170404142612_create_licenses.rb
> +      t.belongs_to :material, index: true
`has_many`

2017-04-07 07:45 UTC, basavind commented on db/migrate/20170404144212_create_states.rb
> +      t.belongs_to :material, index: true
`has_many`

2017-04-07 07:56 UTC, basavind commented
По поводу триггеров `destroy` — нигде их не используй, пока это явно не понадобится исходя  из бизнес-логики, а пока что это не надо. Лучше добавить мягкое удаление во все модели (ну или в большинство), что-нибудь из разряда https://github.com/ActsAsParanoid/acts_as_paranoid или свой concern написать (например как здесь http://artemeff.com/2013/04/21/concerns-v-rails-4.html).

app/models/concerns/associate.rb — удаляй нафиг, так как при изменении бизнес-логики в одной из моделей и изменении параметров связи придется выносить изменяемую связь из под concern (не знаю как по-русски будет) и прописывать отдельно, что в конечном итоге так или иначе приведет к ненужности этого модуля.

2017-04-07 08:13 UTC, basavind commented
Укороченный дамп постгреса, чтобы сравнить со схемой данных — [dump.txt](https://github.com/kursomir/Transfer/files/904939/dump.txt)

2017-04-07 08:19 UTC, basavind commented
И дропни заодно вот этот коммит https://github.com/kursomir/Transfer/pull/7/commits/45f7b0cd23e59f7e543964548f0f795d77e75ae2 пустя остаются тесты, фикстуры и прочее, несмотря на то, что они пока пустые.

2017-04-07 09:20 UTC, mixty1 commented
по поводу destroy, следовал [стайл гайду](https://github.com/arbox/rails-style-guide/blob/master/README-ruRU.md#has_many-has_one-dependent-option)

2017-04-07 09:23 UTC, mixty1 commented
удалил папку тестов [45f7b0c](https://github.com/kursomir/Transfer/pull/7/commits/45f7b0cd23e59f7e543964548f0f795d77e75ae2) потому, что добавил rspec, для тестов

2017-04-09 10:12 UTC, basavind submitted a review, later dismissed

2017-04-09 10:18 UTC, basavind commented
Тут внезапно всплыл косяк — у рельсовой `ActiveRecord` есть свой метод `slice` и добавление связи `slice` к модели ломает какую-то часть функционала (по крайней мере тесты точно). Поэтому я заменил `slice` и `slice type` на `chunk` и `chunk type`, это же надо сделать в схеме #1. 

По всему остальному — пофиксил модели, тесты базовые к ним написал, линтер немного пофиксил.

2017-04-15 11:48 UTC, basavind approved these changes
Думаю можно мержить

2017-04-21 18:47 UTC, merged